apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: I_Love_CityU
    jsonData:
      database: myfypdb
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    editable: true
    isDefault: true 